### ISSUE TITLE
External Rom uploads?

### ISSUE THREAD

**Issue by star-buck** [sukrut-kelkar/kernel_xiaomi_rosy#1]
Hi Sukrut4778,

just asking: It is you who put up your kernels on pling.com page here?
https://www.pling.com/p/1313290/

Thanks.

**Comment by sukrut-kelkar** [comment]
> Hi Sukrut4778,
> 
> just asking: It is you who put up your kernels on pling.com page here?
> https://www.pling.com/p/1313290/
> 
> Thanks.

Yes

**Comment by star-buck** [comment]
Thank you for the confirmation!
